name: com_csith_geniuzpos
description: GeniuzPOS project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.16.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^5.0.0
  cupertino_icons: ^1.0.3
  #--cached_network_image: ^2.2.0+1
  material_design_icons_flutter: ^4.0.5345
  bitsdojo_window: ^0.1.0+1
  device_info: ^2.0.0
  intl: ^0.17.0
  #image: ^2.1.4
  http: ^0.13.3
  data_table_2: ^2.0.3
  #syncfusion_flutter_datagrid: ^19.1.59-beta # will have license : paid
  hover_effect: ^0.6.0
  #mongo_dart: ^0.7.0+2 #--crach with HIVE
  hive: ^1.1.0
 # hive_flutter: ^0.0.0
  #crypto: ^2.0.4
  path_provider: ^2.0.2
  flutter_screenutil: ^1.1.0
  #flutter_pdf_printer: ^1.1.0+1
  pdf: ^3.2.0
  open_file: ^3.2.1
  printing: ^5.5.0
  url_launcher: ^6.0.6
  ping_discover_network: ^0.2.0+1
  barcode_widget: ^2.0.1
  charset_converter: ^1.0.3
  hex: ^0.1.2
  gbk_codec: ^0.3.2
  rxdart: ^0.23.1
 
  utf: ^0.9.0
 
  js: ^0.6.3 
  flutter_js: ^0.5.0+0
  promptpay: ^1.4.0
  qr_flutter: ^4.0.0
  crclib: ^1.0.1
  string_to_hex: ^0.2.2
  show_network_interface_info: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 # hive_generator: ^1.1.0
  build_runner: ^1.0.4
 
  #web_browser: ^0.4.0
 # auto_route_generator: ^0.6.0
 
#dependency_overrides:
#  pdf:
#    path: ../pdf
#  printing:
#    path: ../printing
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon-png/
    - assets/imgs/
    - assets/menu-icon/
    - assets/pos-config/
    - assets/food/
    - assets/memberimg/
    - fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Black.ttf
        - asset: fonts/Kanit-Light.ttf
    - family: Leelawadee
      fonts:
        - asset: fonts/leelawad.ttf
        - asset: fonts/leelawdb.ttf
    - family: Leelawadee UI
      fonts:
        - asset: fonts/LeelawUI.ttf
        - asset: fonts/LeelUIsl.ttf
    - family: Gabriola
      fonts:
        - asset: fonts/Gabriola.ttf
    - family: Micrsoft Sans Serif
      fonts:
        - asset: fonts/micross.ttf
    - family: Calibri
      fonts:
        - asset: fonts/calibri.ttf
        - asset: fonts/calibrib.ttf
    - family: Arial
      fonts:
        - asset: fonts/ARIALN.ttf
        - asset: fonts/ARIALNB.ttf
    - family: Tahoma
      fonts:
        - asset: fonts/tahoma.ttf
        - asset: fonts/tahomabd.ttf
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
