import 'package:com_csith_geniuzpos/data/posfunctions/poscontrolfnc.dart';
import 'package:com_csith_geniuzpos/models/posctrls/poscontrol.dart';

class PosAcm {
  PosAcm();
  List<PosCtrl> posCycleAcm = [
    //-------CYCLE / SIGN-IN 1-7----------------
    PosCtrl(
        itemcode: 'CashierId]1]',
        description: 'รหัสแคชเชียร์ที่ Sign-in เข้าทำงาน  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'PosId]1]',
        description: 'รหัสเครื่อง POS ที่ใช้งาน ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'BeginCash]1]',
        description: 'จำนวนเงินเริ่มต้น ที่ป้อนเข้ามา  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'SignInDateธTime]1]',
        description: 'วันเวลาที่เข้าทำงาน ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'SignOutDateTime]1]',
        description: 'วันเวลาที่ปิดรอบและออกจากระบบ  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'Start-End-ReceipNo]1]',
        description: 'เลขที่เอกสารใบเสร็จ เริ่มและสิ้นสุด ',
        groupcode: 'POSCYCLE',
        valuetext: '000-000-000]000-000-000]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'Start-End-RefundNo]1]',
        description: 'เลขที่เอกสารใบรับคืน เริ่มและสิ้นสุด ',
        groupcode: 'POSCYCLE',
        valuetext: '000-000-000]000-000-000]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    //-------DOC ACM 1-10----------------
    PosCtrl(
        itemcode: 'NetSales]1]',
        description: 'ยอดขายสุทธิ ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'NetSalesNormal]1]',
        description: 'ยอดขายสุทธิรวมของสินค้าราคาปกติ ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'NetSalesPromo]1]',
        description: 'ยอดขายสุทธิรวมของสินค้าราคาโปรโมชั่น ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'NetSalesExVat]1]',
        description:
            'ยอดขายสุทธิรวมของสินค้าที่คิด VAT แต่หัก Vat ออกแล้ว[I/T]',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'NetSalesNonVat]1]',
        description: 'ยอดขายสุทธิรวมของสินค้าที่ยกเว้น VAT ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'VatOfNetSales]1]',
        description: 'VAT ของสินค้าที่คิด VAT ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'VatOfCharge]1]',
        description: 'VAT ของค่าชาร์จ ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),

    //-------ITEM SUMMARY 1-9----------------
    PosCtrl(
        itemcode: 'TotalItemExPrice]2]',
        description: 'สะสมค่า ItemExPrice  ของทุก LineItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalItemDiscount]2]',
        description: 'สะสมค่า ItemDiscount  ของทุก LineItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalItemCharge]2]',
        description: 'สะสมค่า ItemCharge ของทุก LineItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalItemNetExPrice]2]',
        description: 'สะสมค่า ItemNetExPrice  ของทุก LineItem  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalAllocateBillDisc]2]',
        description: 'สะสมค่า AllocateBillDIsc  ของทุก LineItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalItemNetSales]2]',
        description: 'สะสมค่า ItemNetSales  ของทุก LineItem   ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalItemVat]2]',
        description: 'สะสมค่า Vat  ของทุก LineItem  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalDiscAmt]2]',
        description: 'สะสมค่า DiscAmt  ของทุก LineItem  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'TotalChargeAmt]2]',
        description: 'สะสมค่า ChargeAmt  ของทุก LineItem  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    //-------ITEM RECEIPT 1-7----------------
    PosCtrl(
        itemcode: 'ReceiveCash]2]',
        description: 'สะสมค่า Cash Reciept  ของทุก ReceiptItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'ReceiveCreditCd]2]',
        description: 'สะสมค่า CreditCard  ของทุก ReceiptItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'ReceiveDebitCd]2]',
        description: 'สะสมค่า Debit Card ของทุก ReceiptItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'ReceiveCoupon]2]',
        description: 'สะสมค่า Coupon Cash  ของทุก ReceiptItem  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'ReceiveCashCd]2]',
        description: 'สะสมค่า Cash Card  ของทุก ReceiptItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'ReceivePoint]2]',
        description: 'สะสมค่า Point  ของทุก ReceiptItem ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'ReceiveOthers]2]',
        description: 'สะสมค่า Other Receive  ของทุก ReceiptItem   ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    //-----DOC.SUMMARY--1-7------
    PosCtrl(
        itemcode: 'CashSales]1]',
        description: 'ยอดขายเงินสด  ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'RoundReceive]1]',
        description: 'รายได้จากการปัดเศษ รับชำระเงินและเงินทอน ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'CashBalance]1]',
        description: 'BegCash + CashIn - CashOut - CashSales + RoundReceive ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'GrossSales]1]',
        description: 'สะสม TbGrossSales * MulFactor   ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'Discount]1]',
        description: 'สะสม TbDiscount * MulFactor   ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
    PosCtrl(
        itemcode: 'Charge]1]',
        description: 'สะสม TbCharge * MulFactor ',
        groupcode: 'POSCYCLE',
        valuetext: '0]0]',
        valueint: 0,
        valuedbl: 0.01,
        image: PosControlFnc().urlHost + '/pos-config/sum_calcuate.jpg'),
  ];
}
